---
driver:
  name: docker
  #socket: tcp://127.0.0.1:2376
  hostname: {{ cookiecutter.kitchen_formula }}.ci.local
  use_sudo: false


provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  formula: {{ cookiecutter.kitchen_formula }}
  log_level: info
  state_top:
    base:
      "*":
        - {{ cookiecutter.kitchen_formula }}
  pillars:
    top.sls:
      base:
        "*":
          - {{ cookiecutter.kitchen_formula }}
  grains:
    noservices: True


# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
